site_name: MaverickPig的大杂烩

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences

theme:
  name: material
  language: 'zh'

  features:
    - navigation.tabs
    - navigation.tracking
    # - navigation.path          # Sponsors only 
    - navigation.indexes
    - toc.integrate

  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

nav:
  - 如我所见:
      - index.md

  - 书我随想: 
      - 书我随想\index.md

  - 为我所学:
      - 为我所学/index.md
      - PyTorch:
          - 为我所学\PyTorch\index.md
          - 为我所学\PyTorch\数据集与数据处理.md
          - 为我所学\PyTorch\神经网络搭建.md
      - 参数量化:
          - 为我所学\参数量化\VecQ.md
      - 数据结构与算法:
          - 为我所学\数据结构与算法\index.md
          - 为我所学\数据结构与算法\动态规划.md
      - LeetCode:
          - 为我所学\leetcode_notes\index.md
          - 为我所学\leetcode_notes\April_2021.md
          - 为我所学\leetcode_notes\March 2021.md
          - 为我所学\leetcode_notes\September_2021.md