site_name: MaverickPig的大杂烩
site_url: https://maverick618.github.io/

# MD扩展
markdown_extensions:

  # Todo: 暂时不懂  
  - sane_lists
  - pymdownx.magiclink

  - pymdownx.tasklist:
        custom_checkbox: true

  - pymdownx.arithmatex:
        generic: true

  # 元信息
  - meta

  # 通用前置
  - pymdownx.superfences # 提示、警告栏 / 代码块 / 内容标签栏
  - attr_list # 按钮 / 图片
  - pymdownx.snippets # 术语 / 代码块

  # 目录结构
  - toc:
        permalink: true
        toc_depth: 4

  # 术语提示与独立的术语表？ 还不太懂
  - abbr

  #  提示、警告栏
  - admonition
  - pymdownx.details

  # 代码块
  - pymdownx.highlight:
        anchor_linenums: true
  - pymdownx.inlinehilite

  # 内容标签栏
  - pymdownx.tabbed:
        alternate_style: true

  # 表格
  - tables

  # 注脚
  - footnotes

  # 格式化处理
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

  # 图表
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
  # The Markdown in HTML extension allows for writing Markdown inside of HTML
  - md_in_html

  # 列表
  - def_list
  - pymdownx.tasklist:
        custom_checkbox: true

  # 数学公式
  - pymdownx.arithmatex:
        generic: true


# 允许数学公式
extra_javascript:
#   - javascripts/mathjax.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
#   - js/extra.js
  # Todo: Katex 还不懂
  - https://gcore.jsdelivr.net/npm/katex@0.15.1/dist/katex.min.js
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - js/katex.js

# css
extra_css:
  - stylesheets/extras.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

# 主题
theme:
    name: material
    language: zh

  # 评论
    custom_dir: overrides

    palette:
    # Palette toggle for light mode
      - scheme: default
        primary: cyan
        accent: cyan
        toggle:
            icon: material/brightness-7
            name: Switch to dark mode
    # Palette toggle for dark mode
      - scheme: slate
        primary: indigo
        accent: indigo
        toggle:
            icon: material/brightness-4
            name: Switch to light mode

    font:
        text: Noto Serif SC
        code: JetBrains Mono
    features:
      - navigation.tabs
      - navigation.tracking
      - navigation.indexes
      - navigation.top
      - navigation.instant
    # - toc.integrate  # 目录表 嵌入
    # - navigation.path          # Sponsors only 
    icon:
    # 更改mkdocs的logo  
        logo: material/notebook-outline

        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16

plugins:
  # - meta # sponsors only
  - rss
  - search
  - statistics
  - git-revision-date-localized:  # 更新时间
        enable_creation_date: true



nav:
  - 首页: index.md
  - 会议:
      - CC信息安全高等级认证及形式化方法: 会议/CC信息安全高等级认证及形式化方法.md
  - 心之所向:
      - 心之所向: 心之所向/index.md
      - 读书:
          - 读书: 心之所向/读书/index.md
          - 白银时代: 心之所向/读书/白银时代.md
          - 革命时期的爱情: 心之所向/读书/革命时期的爱情.md
  - 计算机科学与技术:
      - 计算机科学与技术: 计算机科学与技术/index.md
      - LeetCode:
          - LeetCode: 计算机科学与技术/LeetCode/index.md
          - April_2021: 计算机科学与技术/LeetCode/April_2021.md
          - March_2021: 计算机科学与技术/LeetCode/March_2021.md
          - September_2021: 计算机科学与技术/LeetCode/September_2021.md
      - 定理证明:
          - Coq:
              - environment: 计算机科学与技术/定理证明/Coq/environment.md
              - intros: 计算机科学与技术/定理证明/Coq/intros.md
              - 函数与证明: 计算机科学与技术/定理证明/Coq/函数与证明.md
          - Isabelle:
              - 随笔记: 计算机科学与技术/定理证明/Isabelle/随笔记.md
          - ucos_correct:
              - init_goodis分析: 计算机科学与技术/定理证明/ucos_correct/init_goodis分析.md
      - 操作系统:
          - Linux进程通信: 计算机科学与技术/操作系统/Linux进程通信.md
          - LiteOS:
              - note: 计算机科学与技术/操作系统/LiteOS/note.md
              - 系统调用分析: 计算机科学与技术/操作系统/LiteOS/系统调用分析.md
      - 数据结构与算法:
          - 数据结构与算法: 计算机科学与技术/数据结构与算法/index.md
          - 动态规划: 计算机科学与技术/数据结构与算法/动态规划.md
      - 杂记:
          - Latex: 计算机科学与技术/杂记/Latex.md
          - ML_notes: 计算机科学与技术/杂记/ML_notes.md
          - Markdown: 计算机科学与技术/杂记/Markdown.md
          - Vmware: 计算机科学与技术/杂记/Vmware.md
          - gdb_notes: 计算机科学与技术/杂记/gdb_notes.md
          - mkdocs_pro&slove: 计算机科学与技术/杂记/mkdocs_pro&slove.md
      - 深度学习:
          - PyTorch:
              - PyTorch: 计算机科学与技术/深度学习/PyTorch/index.md
              - 数据集与数据处理: 计算机科学与技术/深度学习/PyTorch/数据集与数据处理.md
              - 神经网络搭建: 计算机科学与技术/深度学习/PyTorch/神经网络搭建.md
              - 网络训练: 计算机科学与技术/深度学习/PyTorch/网络训练.md
          - 参数量化:
              - VecQ: 计算机科学与技术/深度学习/参数量化/VecQ.md
  - 论文:
      - 操作系统验证:
          - Verification for eChronos OS: 论文/操作系统验证/Verification for eChronos OS.md
      - 程序逻辑与证明:
          - CaReSL: 论文/程序逻辑与证明/CaReSL.md
          - Spoq: 论文/程序逻辑与证明/Spoq.md
          - hoare_logic: 论文/程序逻辑与证明/hoare_logic.md
